openapi: 3.0.0
info:
  title: 'Acquiring Rules API'
  description: 'Acquiring Rules OpenAPI Documentation'
  version: 1.0.0
paths:
  /acquirers:
    get:
      tags:
        - Acquirers
      summary: 'List Acquirers'
      description: 'List All Acquirers'
      operationId: listAcquirers
      responses:
        '200':
          description: 'Acquirer List'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AcquirerResource'
              example:
                -
                  id: 1
                  name: green
                  default: true
                -
                  id: 2
                  name: red
                  default: false
                -
                  id: 3
                  name: blue
                  default: false
  '/scenarios/{id}':
    get:
      tags:
        - 'Payment Scenario'
      summary: 'Get Scenario By Id'
      description: 'Get Scenario By Id'
      operationId: getScenarioById
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: 'Found Scenario Data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentScenarioResource'
        '404':
          description: 'Can''t find any scenario with the given id.'
    put:
      tags:
        - 'Payment Scenario'
      summary: 'Update Payment Scenario'
      description: 'Update Payment Scenario'
      operationId: 'Update Payment Scenario'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateScenarioRequest'
      responses:
        '200':
          description: 'Updated Scenario Data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentScenarioResource'
        '422':
          description: 'Invalid Request'
        '409':
          description: 'Cannot update the scenario, because it conflicts another else.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentScenarioResource'
    delete:
      tags:
        - 'Payment Scenario'
      summary: 'Delete Scenario'
      description: 'Delete Scenario'
      operationId: deleteScenario
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: 'Deleted with success.'
        '404':
          description: 'Can''t find any scenario with the given id.'
  /acquirer-prioritization:
    get:
      tags:
        - 'Acquirer Prioritization'
      summary: 'Get Acquirer Prioritization'
      description: 'Get Acquirer Prioritization By Parameters'
      operationId: 'Get Acquirer Prioritization'
      parameters:
        -
          name: installment
          in: query
          required: true
          schema:
            type: integer
            example: 7
        -
          name: brand
          in: query
          required: true
          schema:
            type: string
            example: mastercard
      responses:
        '200':
          description: 'Acquirer Prioritization Data'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentScenarioAcquirerResource'
        '400':
          description: 'Bad Request'
  /scenarios:
    get:
      tags:
        - 'Payment Scenario'
      summary: 'Search Scenarios'
      description: 'Search Scenarios By Parameters'
      operationId: 'Search Scenarios'
      parameters:
        -
          name: per_page
          in: query
          required: false
          schema:
            type: integer
            example: 10
        -
          name: page
          in: query
          required: false
          schema:
            type: integer
            example: 1
        -
          name: brand
          in: query
          required: false
          schema:
            type: string
            example: mastercard
        -
          name: installment_start
          in: query
          required: false
          schema:
            type: integer
            example: '1'
        -
          name: installment_end
          in: query
          required: false
          schema:
            type: integer
            example: '12'
      responses:
        '200':
          description: 'Search Result'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentScenarioPaginatorResource'
    post:
      tags:
        - 'Payment Scenario'
      summary: 'Create Payment Scenario'
      description: 'Create Payment Scenario'
      operationId: 'Create Payment Scenario'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateScenarioRequest'
      responses:
        '201':
          description: 'Created Scenario Data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentScenarioResource'
        '422':
          description: 'Invalid Request'
        '409':
          description: 'Cannot create the scenario, because it conflicts with an existing one.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentScenarioResource'
components:
  schemas:
    CreateScenarioRequest:
      properties:
        brand:
          type: string
          example: mastercard
        installment_interval:
          properties:
            start:
              type: integer
              example: '1'
            end:
              type: integer
              example: '12'
          type: object
        acquirers:
          type: array
          items:
            properties:
              acquirer_id:
                type: integer
                example: '1'
              priority:
                type: integer
                example: '1'
            type: object
          example:
            -
              acquirer_id: 1
              priority: 1
            -
              acquirer_id: 2
              priority: 2
      type: object
    UpdateScenarioRequest:
      properties:
        brand:
          type: string
          example: mastercard
        installment_interval:
          properties:
            start:
              type: integer
              example: '1'
            end:
              type: integer
              example: '12'
          type: object
        acquirers:
          type: array
          items:
            properties:
              acquirer_id:
                type: integer
                example: '1'
              priority:
                type: integer
                example: '1'
            type: object
          example:
            -
              acquirer_id: 1
              priority: 1
            -
              acquirer_id: 2
              priority: 2
      type: object
    AcquirerResource:
      properties:
        id:
          type: integer
          example: '1'
        name:
          type: string
          example: green
        default:
          type: boolean
          example: 'true'
      type: object
    PaymentScenarioAcquirerResource:
      properties:
        acquirer:
          properties:
            id:
              type: integer
              example: '1'
            name:
              type: string
              example: green
          type: object
        priority:
          type: integer
          example: '1'
      type: object
    PaymentScenarioPaginatorResource:
      properties:
        total_count:
          type: integer
          example: '20'
        current_page:
          type: integer
          example: '1'
        page_size:
          type: integer
          example: '10'
        total_pages:
          type: integer
          example: '2'
        items:
          type: array
          items:
            $ref: '#/components/schemas/PaymentScenarioResource'
      type: object
    PaymentScenarioResource:
      properties:
        id:
          type: integer
          example: '1'
        brand:
          type: string
          example: mastercard
        installments:
          properties:
            start:
              type: integer
              example: '1'
            end:
              type: integer
              example: '12'
          type: object
        acquirers:
          type: array
          items:
            $ref: '#/components/schemas/PaymentScenarioAcquirerResource'
      type: object
